version: "3"
services:
  analysis:
    image: joelnitta/japan_ferns_biogeo:3.6.1
    ports:
      - "8787:8787"
    volumes:
      - ".:/home/rstudio/japan_ferns_biogeo"
    environment:
      DISABLE_AUTH: "true"
    working_dir: /home/rstudio/japan_ferns_biogeo
