---
title: "An update and reassessment of fern and lycophyte diversity data in the Japanese Archipelago"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

An update and reassessment of fern and lycophyte diversity data in the Japanese Archipelago

Atsushi Ebihara & Joel H. Nitta

## Introduction

Ferns and lycophytes or seed-free vascular plants, also traditionally known as ‘pteridophytes’ are a group of plants which have been paid strong attention as research material of biology. Although estimated number of extant species of ferns and lycophytes is only 11916 (Pteridophyte Phylogeny Group, 2016), much less (approximately one twelfth) than seed plant diversity, the frequency of publication of studies used ferns and lycophytes especially in the field of systematics and evolution seems to be high comparing their proportion on number of species. Thus, ferns and lycophytes are relatively rich organisms for information on their diversity. In last centenary, the diversity of ferns and lycophytes in Japan was quite thoroughly studied, and is probably the third best studied area after Europe and North America. Guo et al. (2003) already noticed that the ferns and lycophyte flora in Japan accompanied with rich trait information was worth analyzing determinants of species diversity, abundance and distribution. Even today, there are scarce examples of analyses on fern diversity pattern in a country or wider scale (e.g. Bogonovich et al. 2014, Mountier et al. 2018). A sole serious problem in the analyses by Gao et al. (2003) was the lack of phylogenetic information at that time, but it was completely solved by subsequent studies (Ebihara 2011, Ebihara et al. 2010). In addition, we should note that the occurrence data they used based on Kurata and Nakaike (1979, 1981, 1983, 1985, 1987, 1990, 1994, 1997) did not covered all the species. Reflecting numerous new occurrences and recircumscription of the species based on the results of recent studies, Ebihara (2016, 2017) provided updated distribution maps for all the native taxa in Japan. We intend to publicize up-to-date diversity datasets on ferns and lycophytes in Japan combined with a review of recent progresses and reassessment of the results in Guo et al. (2003). 

## Flora

The studies on fern and lycophyte flora of the Japanese Archipelago initiated with 44 species enumerated in Thunberg (1786)’s “Flora Japonica”. Thereafter the number of recognized species native to there are gradually increasing: 460 species including subspecies and varieties (Makino and Nemoto 1925), ca. 400 species excluding those in Ogasawara (Bonin) and Ryukyu Islands (Tagawa 1959) and 630 species (Iwatsuki 1995). Our latest checklist of native species of Japan ‘FernGreenList ver. 1.01’ (Ebihara et al. 2017a) comprises 691 species (721 taxa including subspecies and varieties [Electronic supplementary material 1]; hereafter call ‘taxa’) belonging to 37 of the 51 families accepted in PPGI (Pteridophyte Phylogeny Group 2016). As almost no uninvestigated area remains in the archipelago, most of the new additions to the flora after the 1990’s are newly segregated species from known ones based on evidences from ploidy levels, enzyme analyses and/or DNA sequences (e.g. Ebihara et al. 2019a, Fujiwara et al. 2018, Hori et al. 2015, 2018a, 2018c, Lin et al. 1994, 1996, Masuyama and Watano 2010, Murakami et al. 1999, Ohta and Takamiya 1999, Serizawa 2015, Takamiya et al. 1997) along with only small number of brand-new records (Ebihara et al. 2014, 2019a). The number of taxa in Japan is nearly identical to that in Taiwan (721 taxa excluding forms and hybrids, Knapp 2014). The strongest floristic affinity is found to the continental part of China sharing 487 taxa (67.5%), almost corresponding to two thirds of the native taxa in Japan (Ebihara 2016, 2017). Accumulated up-to-date information identified 125 endemic taxa (17.3% of the native taxa) to Japan (Ebihara 2018). 

## Interspecific hybrids

Hybrid ferns have been widely utilized as material of evolutionary biological studies (Sigel 2016), and recognition of interspecific hybrids is always their starting points. Besides those 721 taxa, a huge number of interspecific natural hybrid taxa (371 combinations are listed in Ebihara 2017) is an outstanding characteristic of the flora. This is much more than known hybrid combinations in North America (xxx), China (10 were formerly accepted in Flora of China [Wu et al. 2013] and 20 or more combinations were suggested in the notes) and Taiwan (13 listed in Knapp 2014). Such high diversity is most likely a result of efforts on seeking new hybrid combinations by Satoru Kurata (1922-1978) and his pupils, but might be, at least in part, by a geographical effect of the long archipelago extending north to south which enable sympatric occurrence of species with different habitat preferences according climate fluctuation (any example???). It is highly likely that most of the interspecific hybrid individuals in a large part of the world are unrecognized yet, including the cases of miscategorization to non-hybrid taxa. We should mind that only a few combinations of hybridity were verified by artificial crossing, enzyme patterns or nuclear DNA markers and the others are still putative hybrids on morphological basis. An expedient method observing irregular size and shape of spores is often adopted for recognizing interspecific F1 hybrids, but is not always true represented by normal-shaped regular spores produced by homoploid hybrids, Botrychium x silvicola (Ebihara et al. 2015, Sahashi 1983) and other putative homoploid hybrids of Botrychium species in Japan (N. Sahashi, personal communication). An incomplete establishment of reproductive isolation was observed between Osmunda lancea, a rheophytic species endemic to Japan and its closest relative O. japonica, and their ‘hybrid’ O. x intermedia is actually hybrid swarms including not only F1 but also F2 or later-generation hybrid (Yatabe et al. 2009, 2011). Fern interspecific hybrids have long been believed to occur in places where sporophytes of their two parent species are sympatric, and this idea was an important ground for identification of putative parentages. However, our studies demonstrated a number of examples of sterile interspecific hybrid unaccompanied by their parental species. One of the extreme cases is found in a dennstaedtioid fern Monachosorum x arakii which was originally considered as an endemic species to Japan. Our study (Ebihara et al. 2016) concluded that it is a sterile hybrid between Monachosorum henryi and M. nipponica, the former is not currently distributed in Japan but in Taiwan, continental China and Himalaya. Although it is somewhat a special case with strong vegetative reproduction ability not only with rhizomes but also with bulbils making relict distribution possible, we should always hypothesize any possible combination of hybrid parentages as flexible as possible. Apart from relict distribution, we obtained strong evidences for contribution of independent gametophytes to formation of hybrid sporophytes in Vandenboschia (Ebihara et al. 2009).

## Occurrence data and regional species richness

Eight volumes of "Illustrations of Pteridophytes of Japan" (Kurata and Nakaike, 1979, 1981, 1983, 1985, 1987, 1990, 1994, 1997) were a pioneer work of a nationwide organism distribution survey by citizens in Japan. Along with brief description about each species, these books featured 10 km-grid based distribution maps vouchered by ca. 180000 specimens collected by the members of the Nippon Fernist Club. A large part of the specimens presently deposited in the herbarium of National Museum of Nature and Science (TNS) were recently re-identified accommodating up-to-date species circumscription, and ca. 35000 specimens which are new records on the 10 km-grids were newly collected by the club members. Occurrences based on specimens are usually regarded as presence-only data, but present grid maps can be virtually regarded as presence/absence data as the results of the members’ extensive searching in the field. For the convenience in reusing the occurrence data, a list of specimens which assure the distribution maps in Ebihara (2016, 2017) are publicized here, and it contains 216687 herbarium specimen records (Electronic supplementary material 2). We should note that our policy for the dataset is to include specimens or specimen-images examined by ourselves (only exception is Isoetes occurrences which cited from a specimens list provided by Takamiya et al. [1997]). At least one species is recorded in 4343 of 4853 grids (89.5 %), and the species occurred in the maximum number of grids is Pteridium aquilinum subsp. japonicum (Dennstaedtiaceae) recorded in 2777 grids (57.2%).
Even not included in present dataset, much larger number of specimen data without images are available on-line via Science Museum Net (http://science-net.kahaku.go.jp/) which is a portal of natural history specimens deposited in museums in Japan, and the occurrence data are also searchable in the GBIF data portal (https://www.gbif.org/). As of May 23, 2019, Japan is the country of locality with the largest number of fern and lycophyte specimens in GBIF, totally 531311 occurrences.
In the summary of species richness in 10 km-grids excluding nothotaxa (Fig. 1a), the grids with the highest (212 taxa, grid code: 453034) and the second highest diversity (210 taxa, grid code: 453044) are found in the mountain area of Yakushima Island, located south of Kyushu including the island’s highest peak (Mt. Miyanoura, 1936 m in elevation). The third highest grid (202 taxa, grid code 503547) is located in the area covering Nachi-no-taki Falls in southern part of Wakayama Prefecture, southern Honshu.

By adding phylogenetic information, we are able to overview the diversity distribution patterns by a different measure from species number. We updated the rbcL sequence dataset to cover 97.8 % of the native taxa by making several additions and corrections to that prepared by Ebihara et al. (2010) (Electronic supplementary material 1), and then Phylogenetic Diversity (PD, “the minimum total length of all the phylogenetic branches required to span a given set of taxa on the phylogenetic tree”, Faith 1992, 2006) on a tree for every grid was calculated using Phylogenetic Diversity Analyzer ver. 1.0.3 (Chernomor et al. 2015). In the analysis with a dataset covering all ferns and lycophyte taxa considering the tree unrooted (Fig. 1b), the highest PD value was obtained in a grid in Wakayama Prefecture (grid code: 503547), the second highest one in the northern part of the Okinawa Island (grid code: 402801) and third largest one in Iriomote Island (grid code: 362346) located in the southwesternmost part of the Archipelago. These rankings were not significantly changed when we analyzed a dataset with only fern occurrences rooted by a lycophyte (Lycopodium clavatum var. nipponicum) (Fig. 1c). In the result of PD analyses, the Yakushima grid (grid code: 453034) with maximum species richness was ranked 12th in the PD analysis using ferns+lycophytes, and 10th in that only using ferns, respectively. The disparity of the results might suggest the difference in their constituent species – species richness in Yakushima Island is resulted from presence of some species rich genera (e.g. 19 taxa of Dryopteris, 16 taxa of Diplazium, 14 taxa of Athyrium).

Our updated occurrence data supported the trend that species with seasonal-green phenology showed wider distribution than evergreen species suggested by Guo et al. (2003), but it is probably an artifact caused by small land areas at lower altitudes in the country where evergreen species dominate. Guo et al. (2003) also suggested species with multiple reproductive modes showed wider distribution areas than species with a single reproductive mode. However, our data did not support this trend (mean numbers of grids, sex.+apo. = 356.63 (n = 8), sex. = 367.01 (n = 413), apo. = 314.59 (n = 79), none of the combination differs significantly in paired t-test) – the result seems to be strongly affected by species circumscription and presumably some “species with multiple reproductive modes” in Guo et al. (2003) are separated into multiple taxa with each single mode in present treatment. Even though their distribution area sizes are not significantly different, apomictic taxa show significantly narrower latitudinal range than sexual ones (mean degree of ranges: sex. = 7.73 and apo. 6.01, p < 0.001 in paired t-test), and it coincides with the result by Tanaka et al. (2014) that represented smaller range sizes of apomicitic ones both in latitude and elevation. Also the southerly distribution phenomenon of apomicitic species which was presumed a result of poor cold-hardiness of gametophytes of apomictic species having larger cell sizes (Tanaka et al. 2014), was confirmed in present data (Fig. 1d, e). The trend that narrower distribution of polyploid taxa (Guo et al. 2003) is not supported by present data excluding apomictic species (average number of grids, sexual diploid = 337.14, sexual polyploid = 370.51) – the trend probably came out by narrower distribution of apomictic species which are dominated by triploid.

## Cytotaxonomic data

Even today chromosome numbers of ferns and lycophytes which are important clues for knowing the plant’s ploidy level and reproductive mode as well as basic chromosome numbers, which were used as information to infer phylogenetic affinities before the introduction of DNA sequencing. Researchers in Japan stimulated by Irene Manton’s leading work “Problems of Cytology and Evolution in the Pteridophyta” (Manton 1950) actively made chromosome counts of ferns and lycophytes using the squash technique in the second half of the 20th century, and more than 150 papers had been published – all the counts on Japanese material before 1996 was indexed by Takamiya (1996). Additions have been continuously made, and Nakato and Ebihara (2016) summarized that the information drawn from Japanese individuals is available for 74 % of the native taxa (61 %, if nothotaxa are counted) – it is a much higher coverage compared with other areas of East Asia (e.g. ca. 27 % in China, Cheng and Zhang [2010]) and the second highest coverage in Asia following India (ca. 89 %, Bir and Verma [2010]). Further addition is highly needed for ascertaining some early records without preserving voucher specimen, and for detecting infraspecific polyploidy and/or multiple reproductive modes overlooked by previous superficial samplings as well as unsampled taxa. Flow cytometry is recently used for inferring ploidy levels of large number of samples belonging to a closely related species groups (e.g. Ebihara et al. 2005, Fujiwara et al. 2018, Hori et al. 2015, Nitta et al. 2011), but the method always requires at least one control sample whose ploidy level was confirmed by chromosome counts. Flow cytometry analyses using not only fresh leaves but also recently collected spores in herbarium specimens, succeeded in some ferns (Kuo and Huang 2017), might accelerate data accumulation.  

## Threatened species

Latest national red list of Japan (Ministry of the Environment, Japan 2019) included more than one third of the native fern and lycophyte taxa (260 in total, 6 EX, 3 EW, 85 CR, 59 EN, 68 VU, 38 NT and 1 DD; see Fig. 1f for the distribution of richness). The largest threat for ferns is herbivory of the sika deer distributed throughout the archipelago which obviously increased after 1980’s (Takatsuki 2009). In particular, species growing on the forest floor (e.g. Athyrium, Terada and Takamiya 2006) undergo severe damage, and several narrowly distributed species in Kyushu and Yakushima Island became almost extinct or only found inside deer fences. Although national law for endangered species is recently expanding objective fern and lycophyte species which are proscribed collection and sellout (28 species as of May 2019), it is apparently not directly effective for preventing herbivory of deer. There are still a few reports of conservation activities and researches on ferns and lycophytes in Japan: ubiquitous genotyping of Athyrium viridescentipes (Izuno et al. 2012) and clarifying origin and propagation from spore in Dryopteris shibipedis (Ebihara et al. 2012) which was extinct in the wild. Despite 70 of the 260 taxa in the latest national red list are endemic species to Japan, they are neither assessed nor listed in the IUCN Red List as globally threatened species as of May 2019 (IUCN 2019).

## Introduced species

Compared with flowering plants, number of naturalized species of ferns and lycophytes is quite small in the Japanese Archipelago, and they are almost uninvolved with the invasive species issue. Selaginella uncinata (Selaginellaceae) and Pityrogramma calomelanos (Pteridaceae) are two of scarce examples of relatively widespread introduced species in the country (Ebihara 2016). Dryopteris intermedia (ref), D. carthusiana (ref) (Dryopteridaceae) and Dennstaedtia punctilobula (Dennstaedtiaceae) (Ueno et al. 2019) were probably introduced with sprayed seeds on banks and only collected in each one or a few localities. Azolla cristata (Salviniaceae) is the only invasive fern species controlled by national low (Invasive Alien Species Act), but is often troubled in identification due to morphologically similarlity to an endangered and endemic species, A. japonica. Another similar species, Azolla filiculoides is still controversial on its natural distribution in Japan (Ebihara 2016, Suzuki et al. 2005). Selaginella moellendolffii (Selaginellaceae), Psilotum nudum (Psilotaceae), Adiantum capillis-veneris, Pteris vittata (Pteridaceae) and Thelypteris dentata (Thelypteridaceae) have certain natural distribution in the subtropical areas of the country, but are more frequently found as escaped plants from greenhouses. Murakami et al. (2008) demonstrated a range expansion of Thelypteris dentata facilitated by urbanization in Kinki District, Japan. The natural habitat of Cyrtomium falcatum subsp. falcatum is restricted to coastal areas (Ebihara et al. 2017a, Matsumoto 2003), and scattered occurrences in urban environments (Ebihara 2017) in inlands are probably introduced ones.

## Reticulate evolution

Species complexes or aggregate species exhibiting wide ranges of continuous morphological variation are quite commonly known in ferns and lycophytes (Haufler 1996), and this trend seems to be true for the flora of Japan. In case of that interspecific F1 hybrids make the species boundaries ambiguous, we could usually find distinct gaps between them by removing their hybrid individuals suggested by irregular-shaped spores with low germination rates (e.g. Ohta and Takamiya 1999 in the Diplazium mettenianum complex). When interspecific hybrids overcome sterility by chromosome doubling, the situation becomes more complicated and the biological units composing the complex are not easily clarifiable solely by morphological approach. The allopolyploids of hybrid origins often re-hybridize with their parental species --- such "reticulate evolution" process became well-known after the study on Appalachain Asplenium (Wagner 1954). Apparently similar approach combining chromosome and morphological observations was rarely adopted to Japanese species. After 1990's, allozyme analyses were frequently applied to the fern complexes in Japan, and plastid sequences often accompanied as indicators of maternal lineage (e.g. Darnaedi et al. 1990 in Dryopteris yakusilvicola and its related species, Lin et al. 1996 in Odontosoria, Shinohara et al. 2010 in Lepisorus, Takamiya and Ohta 2001 in Diplazium). In 2000's, single or low copy nuclear DNA regions became popularly used as biparently inherited markers (e.g. Ishikawa et al. 2002), and sequence polymorphisms were efficiently isolated by cloning or the SSCP (Single Strand Conformation Polymorphism) method (initiated by Ebihara et al. 2005 in the Vandenboschia radicans complex, thereafter applied to various fern groups including Ceratopteris [Adjie et al. 2007]), the Pteris cretica complex [Jaruwattanaphan et al. 2013], the Davallia repens complex [Chen et al. 2014], the Asplenium normale complex [Fujiwara et al. 2017]). Although next-generation sequencing is widely used in phylogenetic and population genetic studies on various organisms in recent years, it is still not popularly applied to analyses on species complexes of ferns and lycophytes mainly due to technical difficulties in removing chimeral contigs identifying and homologous copies from the obtained sequences. More recently Rothfels et al. (2017) succeeded in phylogenetic analysis on a polyploid complex of cystoptreroid ferns using PacBio sequences, and the method is highly expected to apply wide ranges of fern complexes.

## Species complexes involved with apomixis

Further complexity is provided when apomictic reproduction (reviewed in Grusz et al. 2016) is concerned. The topic, apomixis or apogamy in ferns has attracted researchers in Japan as the reproductive mode is known in a higher rate in the native taxa of the country (13 % of the species whose reproductive modes are known in Takamiya 1996; 12 % in present study) than the average rate in the world (ca. 10 %, Grusz et al. 2016). Apomixis plays a role not only in overcoming sterility of interspecific hybrids (e.g. Park and Kato 2003) but also making secondary hybridization by fertilization between a sperm produced by the ‘hybrid’ and an egg of sexually reproducing races. This process can generates countless apomict races with various genomic combinations which are morphologically continuous, and the races are often controversial about circumscription of ‘species’ (a polymorphic species versus numerous morphologically ill-defined species). One of the best known apomict complexes troublesome in identification, the Dryopteris varia complex was recently clarified their internal relationships using single-copy nuclear DNA markers (Hori et al. 2014, 2015, 2016), and analyses on several other complexes are in progress. However, even using molecular markers, we often meet an obstacle that we cannot find progenitors or sexual diploids of the complex. Hori et al. (2018d) discovered several sexual diploid individuals of Dryopteris in southern China, and as the progenitors the newly found diploids well explained the reticulate evolution processes of the D. erythrosora complex in Japan which had bothered researchers for many years (Hori et al. 2018b). This case supported the hypothesis by Gao et al (2003): “The ancestral sexual species of many Japanese apogamous species occur in China, suggesting that these species might have migrated from China”. In contrast to these successful clarifications, we are still struggling with more challenging complexes. The species of Cyrtomium (Dryopteridaceae) in Japan typically match this pattern: 12 native species and subspecies are all triploid apomicts except for two subspecies of C. falcatum (subsp. australe and subsp. littorale, sexual diploid) and C. devexiscapulae (sexual tetraploid) (Ebihara et al. 2017a, Matsumoto 2003). Despite careful exploration of sexually reproducing individuals by examining spore number per sporangium in herbarium specimens collected in China, a large part of them are apomictic and sexual ones were found less frequently in geographically narrow ranges (Mitsuta 1986, 1988). The Pteris fauriei complex is probably in similar situation, and it includes several endemic ‘species’ to Japan which are diploid or triploid apomict (Ebihara 2016). The “Diploids-First Approach” (Beck et al. 2010) is a principle for the studies on fern reticulate complexes, but we should mind that diploids are not always present nearby including possible extinction in complexes involved with apomixis.

## Species concept

It is obvious that recent increase of recoded taxa in Japan is largely owing to transition from morphological species concept to biological or evolutional ones. In many cases, subsequent taxonomic revisions were published after analyses on certain species complexes. Although we have not reached any final consensus on the concept, strict application of neither biological species concept nor evolutionary species one seem to be preferred by recent studies. In particular, an autotetraploid, which should be treated as an independent species from a diploid sharing same genome in the biological species concept, is more often treated as infraspecific polyploidy. Ebihara et al. (2005, 2009) circumscribed a new allotetraploid species Vandenboschia hokurikuensis including recurrently originated (at least twice, based on maternally inherited plastid sequences). In practice, every allopolyploid with different combination of diploid progenitor species requires a name. Among the 195 taxa in Japan which sexual polyploid (tetraploid or higher) was reported for, evidences for judging autopolyploidy/allopolyploidy are available in 34 taxa (17.4 %). Only four of them (Asplenium boreale [Fujiwara et al. 2017], Asplenium pekinense [Lin et al. 2013], Pteris deltodon [Jaruwattanaphan et al. 2013], and Lepisorus tosaensis [Fujiwara et al. 2018]) are probable autopolyploid (autotetraploid) and the remaining 30 taxa are allopolyploid. Some of currently accepted infraspecific taxa defined to correspond to ploidy levels (e.g. diploid Lycopodium clavatum var. nipponicum vs. tetraploid var. asiaticum [Takamiya 1989]; tetraploid Deparia petersenii var. petersenii vs. hexaploid var. yakusimensis [Shinohara et al. 2003]) might be classified into different species if future studies clarify differences in their genomic combinations.

We are often faced with a problem about taxonomic treatment for apomictic races. As they are asexually reproducing, the biological species concept is not applicable, and in fact several studies had no other choice than suspension of corresponding taxonomic treatment (e.g. Chen et al. 2014, Nitta et al. 2011). Another trouble is on their nomenclatural categories: i.e. should we describe apomictic races of hybrid origin as nothotaxa? Recircumscription of species recently made by Hori et al. (2018a) for the Dryopteris varia complex is probably the most easily acceptable decision, which is, providing a species name at non-hybrid category for every apomictic race with different combination of sexually reproducing progenitors. This treatment resulted a split of Dryopteris hikonensis to three apomictic species namely D. hikonensis s.s. (= D. protobissetiana x D. varia), D. erythrovaria (= D. caudipinna x D. protobissetiana x D. varia) and D. subhikonensis (= D. protobissetiana x D. saxifraga x D. varia). It should be noted that we treated some individuals originated from hybridization between an apomictic race and sexual species which showing lower spore germination rates and/or growing not vigorously in the wild as nothotaxa in FernGreenList (Ebihara et al. 2016). The categorization largely depends on our observation and experiences, and we could not always strictly border them.
 There is no standard taxonomic treatment for the case that both sexual race and apomictic race coexist in a single species. While in many cases both reproductive modes are not distinguished taxonomically (e.g. Pteris oshimensis, Phegopteris connectilis and Dryopteris chinensis), the apomicitc race of Pteris terminalis are distinguished at varietal rank (var. fauriei, Ebihara et al. 2017b) considering its morphological distinctness and failure of finding unique allele in the apomictic race.

## Gametophytes

Our knowledge about gametophytes of ferns and lycophytes is considerably limited compared with that in sporophytes, nevertheless Japan is one of the world’s most information-rich areas for fern gametophytes. Two dennstaedtioid genera, Coptodipteris (‘Coptidipteris’) and Fuziifilix described by Nakai and Momose (1937) are scarce examples segregated based on gametophyte characters, even though they are probably merged into one of the two clades of Dennstaedtia (Perrie et al. 2015). Momose (1967) observed and illustrated gametophytes of ca. 330 species mostly native to the country using cultured ones from spores. Although he succeeded in culture almost only for cordate gametophytes, subsequent researchers observed non-cordate gametophytes which grow and maturate usually slower than cordate ones (e.g. Hymenophyllaceae [Yoroi 1972, 1976, 1992], Haplopteris (Pteridaceae) [Yoroi 1975], Pleurosoriopsis (Polypodiaceae) [Ebihara et al. 2019b, Masuyama 1975] and Botrychium (Ophioglossaceae) [Takahashi and Imaichi 2007]).

Ebihara et al. (2010) completed setting up a country scale DNA barcode library (plastid rbcL and trnH-psbA regions, covering ca. 94 % of native fern and lycophyte taxa) which is quite useful for identification of gametophytes in the wild. Our preliminary sampling demonstrated an interesting phenomenon that non-cordate gametophytes frequently ‘independent’ or occur far from their counterpart sporophytes localities while cordate ones are almost always sympatric with conspecific sporophytes (Ebihara et al. 2013). This is also true for independent filamentous gametophytes of Vandenboschia as mentioned above, and some of the independent gametophytes might be solely gametophytes distributed in the country (Haplopteris sp. in Yakushima Island, Kuo et al. 2017). Expanded samplings of gametophytes in the wild will shed light on more and more independent ones. In another aspect, identification using DNA barcode enabled detection of fungal association of wild fern gametophytes (Ogura-Tsujita et al. 2013, 2016). Although they discussed possible correlation between gametophyte cushion structure and arbuscular mycorrhizal association, much wider taxonomic and geographical samplings are necessary for understanding the evolutional trend as well as for comparison with symbiotic fungi in sporophytes (reviewed by Lenhert et al. 2016, Pressel et al. 2016).

## Taxonomic key characters

Ebihara (2016, 2017) publicized matrices for major morphological characters frequently used for identification keys for all the 721 native ferns and lycophytes in Japan. All the quantitative characters were newly measured by the members of the Nippon Fernist Club in ten randomly selected herbarium specimens per taxon. As these data are much more useful in an electric form than a printed version, we provide the data file (Electronic supplementary material 3) in the format for Lucid 3.3, which is a free version of the software for interactive keys available at http://www.lucidcentral.com/en-us/home.aspx.

## Future perspective

Albeit none of the genus accepted in PPGI (Pteridophyte Phylogeny Group 2016) is endemic to the archipelago, recent studies revealed several infrageneric clades distributed centered in and/or representing the highest diversity there. Spicantopsis, the most recently resurrected genus in Blechnaceae is now subendemic to Japan (2 endemic species and 1 species in Japan and Taiwan) and its ancestor estimated to migrate from North America to East Asia in ca. 85 mya (Gabriel y Galan et al., in press). Apart from Spicantopsis, we could find at least three groups exhibiting significant diversity in there: Deparia subsect. Athyriopsis (Kuo et al. 2016, 2018), “Clades VI + VII” of Lepisorus (Wang et al. 2009), “the HYSUFI clade” of Polystichum (Le Pechon et al. 2016). Clarification of their speciation and biogeographic histories is expected to contribute for understanding flora formation in East Asia and the Far East. 

Regional flora should never conclude in itself but be compared with those of neighboring regions toward a global view. In widespread species or species complexes, we often troubled when applying the results of evidential revisional works with limited geographical coverage of samplings to regional flora of unsampled areas. As Shrestha and Zhang (2014) demonstrated in the Chinese populations, Huperzia serrata sensu lato (Lycopodiaceae) is never a single species but an aggregation of multiple biological units, and it was supported by DNA content analyses using populations in Aichi Prefecture of Japan (Aman et al. 2011). Unfortunately, these findings were not reflected but recognized only Huperzia serrata s.l. in FernGreenList 1.0.1 (Ebihara et al. 2016) as we could not drew reliable synthesis of these results for applying Japanese populations. There are a number of native species or groups in Japan which are awaiting careful comparison with published results mostly generated in China and other Asian countries (e.g. Pteridium [Zhou et al. 2015], Hymenasplenium [Xu et al. 2018]) and Leptochilus [Zhang et al. 2019].

Contrasting to a consensus on familial classification of ferns and lycophytes almost achieved in PPGI (Pteridophyte Phylogeny Group 2016), generic classification proposed in the system requires a good deal of update and emendation based on newly generated evidences. For example, the 30-generic system of Thelypteridaceae adopted in the PPGI system seems hardly applicable to the species in Japan due to generation of a nothogenus x Chrinephrium (x C. insulare) and due to uncertain placement for the species formerly included in Parathelypteris (e.g. the material of “Parathelypteris nipponica” from China used in the phylogeny of He and Zhang (2012) and Almeida et al. (2016) is in question for the identification). It is important to publicize data on East Asian material with accurate identification working as bases for generic recircumscription in forthcoming “PPGII”.

Accumulation of data on ploidy and reproductive modes along with recognition of proper taxonomic units and their distribution data enables us to discuss about various characteristics of ferns and lycophytes as an organism group such as a proportion of polyploids and a proportion of apomict. In a country scale, combined analyses between the occurrence data provided by the present study and various kinds of geographic variables may yield further new findings but we here confine preliminary ones. We finally note an interesting finding which is not exposed in present maps: a hotspot of diploid progenitors which are probable palaeoendemics on the riverside in Amami-oshima Island, central Ryukyu. The hotspot is represented by at least four examples: 1) Polystichum obae (Dryopteridaceae), an endemic diploid species (Takamiya 1996) with a quite small population, and is sister to a clade consisting of tetraploid P. polyblepharon (Takamiya 1996) + diploid P. parvipinnulum (Tsai and Shieh 1985) in plastid phylogeny (Le Pechon et al. 2016); 2) Coniogramme gracilis (Pteridaceae), a diploid species (Kurita 1972) endemic to the island, and is presumably a progenitor of widespread tetraploid C. japonica (Kurita 1963); 3) Diplazium amamiana (Athyriaceae), a diploid species (Takamiya et al. 1999) endemic to the island, and sister to widespread apomictic species D. hachijoense in plastid phylogeny (Ebihara 2011, Wei et al. 2013); 4) Pteris oshimensis (Pteridaceae), a widespread species, and sexual diploid is only found in Amami Islands in contrast to widespread apomictic races (Nakato and Ebihara 2016). The pattern, sexual diploid confined to Amami Islands vs. widespread polyploids, shared by these four pairs strongly suggests that the island is a relic for ancestral diploids. However, this may be one of many outcomes from our present datasets of ferns and lycophytes in Japan. It is highly expected to be drawn evolutionary scenarios for formation of flora and diversity by accumulation and integration of huge but reliable information.

References

Adjie B, Masuyama S, Ishikawa H, Watano Y (2007) Independent origins of tetraploid cryptic species in the fern Ceratopteris thalictroides. J Plant Res 120:129-138
Almeida TE, Hennequin S, Schneider H, Smith AR, Batista JAN, Ramalho AJ, Proite K, Salino A (2016) Towards a phylogenetic generic classification of Thelypteridaceae: Additional sampling suggests alterations of neotropical taxa and further study of paleotropical genera. Molec Phylogen Evol 94: 688-700
Aman A, Kato J, Serizawa S (2011) Studies on the Huperzia serrata group (Lycopodiaceae) in Japan (1). Nuclear DNA contents in the populations of Aichi prefecture. Shidekobushi 2:23-32 (in Japanese with English summary)
Beck JB, Windham MD, Yatskievych G, Pryer KM (2010) A diploids-first approach to species delimitation and interpreting polyploid evolution in the fern genus Astrolepis (Pteridaceae). Syst Bot 35:223-234
Bir SS, Verma SC (2010) Chromosome Atlas of the Indian Pteridophytes (1951-2009). Bishen Singh Mahendra Pal Singh, Dehra Dun
Bogonovich M, Robeson S, Watson M (2014) Patterns of North American fern and lycophyte richness at three taxonomic levels. Amer Fern J 103:193-214
Chen CW, Ngan LT, Hidayat A, Evangelista L, Nooteboom HP, Chiou WL (2014) First insights into the evolutionary history of the Davallia repens complex. Blumea 59:49-58
Cheng X, Zhang SZ (2010) Index to chromosome numbers of Chinese Pteridophyta (1969-2009). J Fairylake Bot Gard 9:1-58
Chernomor O, Minh BQ, Forest F, Klaere S, Ingram T, Henzinger M, von Haeseler A (2015) Split diversity in constrained conservation prioritization using integer linear programming. Methods Ecol Evol 6:83-91 DOI: 10.1111/2041-210X.12299
Darnaedi D, Kato M, IwatsukiK (1990) Electrophoretic evidence for the origin of Dryopteris yakusilvicola (Dryopteridaceae). Bot Mag (Tokyo) 103:1-10
Ebihara A (2011) RbcL phylogeny of Japanese pteridophyte flora and implications on infrafamilial systematics. Bull Nat Mus Nat Sci B 37:63-74
Ebihara A (2016) The Standard of Ferns and Lcyophytes in Japan 1. Gakken Plus, Tokyo (in Japanese) 
Ebihara A (2017) The Standard of Ferns and Lcyophytes in Japan 2. Gakken Plus, Tokyo (in Japanese)
Ebihara A (2018) A checklist of ferns and lycophytes endemic to Japan (edition March 2018) http://www.kahaku.go.jp/research/activities/project/hotspot_japan/endemic_list/
Ebihara A, Ishikawa H, Matsumoto S, Lin SJ, Iwatsuki K, Takamiya M, Watano Y, Ito M (2005) Nuclear DNA, chloroplast DNA, and ploidy analysis clarified biological complexity of the Vandenboschia radicans complex (Hymenophyllaceae) in Japan and adjacent areas. Amer J Bot 92:1535-1547.
Ebihara A, Ito M, Nagamasu H, Fujii S, Katsuyama T, Yonekura K, Yahara, T (2016) Fern GreenList ver. 1.01 http://www.rdplants.org/gl/
Ebihara A, Matsumoto S, Ito M (2009) Hybridization involving independent gametophytes in the Vandenboschia radicans complex (Hymenophyllaceae): a new perspective on the distribution of fern hybrids. Molec Ecol 18:4904-4911
Ebihara A, Matsumoto S, Kato M (2012) Origin of Dryopteris shibipedis (Dryopteridaceae), a fern species extinct in the wild. J Plant Res 125:499-505
Ebihara A, Matsumoto S, Mazumdar J, Yamamoto K (2017a) Updates of taxonomic treatments for ferns of Japan 2. Athyrium and Cyrtomium. Bull Natl Mus Nat Sci B 43:19-25
Ebihara A, Morita H, Yamamuro K (2019a) Diplazium megaphyllum (Athyriaceae) new to Japan, discovered in Tokunoshima Island. J Jpn Bot 93:404-406 (in Japanese with English summary)
Ebihara A, Nakato N, Amoroso VB, Hidayat A, Kuo LY (2016) Monachosorum arakii Tagawa (Dennstaedtiaceae) is a relict "international" hybrid: A reassessment of the Monachosorum species. Syst Bot 41:586-595
Ebihara A, Nakato N, Jaruwattanaphan T (2017b) A new taxonomic treatment for the apogamous counterpart of Pteris terminalis (Pteridaceae). Phytotaxa 314:73-80
Ebihara A, Nakato N, Kuo LY, Miyazaki H, Serizawa S (2019b) Allopolyploid origin and distribution range of Acystopteris taiwaniana (Cystopteridaceae: Polypodiales). Acta Phytotax Geobot 70:19-28
Ebihara A, Nakato N, Matsumoto S (2015) Updates of taxonomic treatments for ferns of Japan 1. Botrychium, Osmolindsaea and Pteris. Bull Natl Mus Nat Sci B 41:15-24
Ebihara A, Nakato N, Saito Y, Oka T, Minamitani T (2014) New records of Asplenium varians (Aspleniaceae) and two new hybrids in Japan. Acta Phytotax Geobot 65:53-65
Ebihara A, Nitta JH, Ito M (2010) Molecular species identification with rich floristic sampling: DNA barcoding the pteridophyte flora of Japan. PLoS ONE 5(12):e15136
Ebihara A, Nitta JH, Matsumoto Y, Fukazawa Y, Kurihara M, Yokote H, Sakuma K, Azakami O, Hirayama Y, Imaichi R (2019b) Growth dynamics of independent gametophytes of Pleurosoriopsis makinoi (Polypodiaceae). Bull Nat Mus Nat Sci B 45:77-86
Ebihara A, Yamaoka A, Mizukami N, Sakoda A, Nitta JH, Imaichi R (2013) A survey of the fern gametophyte flora of Japan: Frequent independent occurrences of noncordiform gametophytes. Amer J Bot 100:735-743
Faith DP (1992) Conservation evaluation and phylogenetic diversity. Biol Conserv 61:1-10
Faith DP, Baker AM (2006) Phylogenetic diversity (PD) and biodiversity conservation: some bioinformatics challenges. Evol Bioinform Online 2006:2 121-128
Fujiwara T, Serizawa S, Watano Y (2018) Phylogenetic analysis reveals the origins of tetraploid and hexaploid species in the Japanese Lepisorus thunbergianus (Polypodiaceae) complex. J Plant Res 131:945-959
Fujiwara T, Uehara A, Iwashina T, Matsumoto S, Chang YH, Chao YS, Watano Y (2017) Allotetraploid cryptic species in Asplenium normale in the Japanese Archipelago, detected by chemotaxonomic and multi-locus genotype approaches. Amer J Bot 104:1390-1406
Gabriel y Galan JM, Molino S, Sessa EB, Wasowicz P (in press) A multi-character analysis of Struthiopteris leads to the rescue of Spicantopsis (Blechnaceae, Polypodiopsida). Taxon
Grusz AL (2016) A current perspective on apomixis in ferns. J Syst Evol 54:656-665
Haufler CH (1996) Species concepts and speciation in pteridophytes.In: Camus JM, Gibby M, Johns RJ eds. Pteridology in perspective. Proceedings of the Holttum Memorial Pteridophyte Symposium, Kew 1995. Kew: Royal Botanical Gardens. pp. 291-305
Guo Q, Kato M, Ricklefs RE (2003) Life history, diversity and distribution: a study of Japanese pteridophytes. Ecography 26:129-138
He LJ, Zhang XC (2012) Exploring generic delimitation within the fern family Thelypteridaceae. Molec Phylogen Evol 65:757-764 
Hori K, Ebihara A, Murakami N (2018a) Revised classification of the species within the Dryopteris varia complex (Dryopteridaceae) in Japan. Acta Phytotax Geobot 69:77-108
Hori K, Ebihara A, Nakato N, Murakami N (2015) Dryopteris protobissetiana (Dryopteridaceae), a new diploid sexual species of the Dryopteris varia complex (subg. Erythrovariae, sect. Variae) from Yakushima, Kagoshima, Japan. Acta Phyotax Geobot 66:47-57
Hori K, Tono A, Fujimoto K, Kato J, Ebihara A, Watano Y,  Murakami N (2014) Reticulate evolution in the apogamous Dryopteris varia complex (Dryopteridaceae, subg. Erythrovariae, sect. Variae) and its related sexual species in Japan. J Plant Res 127:661-684
Hori K, Watano Y, Murakami N (2016) Hybrid origin of the apogamous fern Dryopteris hondoensis (Dryopteridaceae). Acta Phytotax Geobot 67:133-146
Hori K, Zhou XL, Shao W, Yan YH, Ebihara A, Wang RX, Ishikawa H, Watano Y, Murakami N (2018b) Hybridization of the Dryopteris erythrosora complex (Dryopteridaceae, Polypodiidae) in Japan and adjacent areas. Hikobia 17:299-313
Hori K, Zhou XL, Shao W, Yan YH, Wang RX, Murakami N (2018d) New diploid sexual cytotypes of Dryopteris sect. Erythrovariae (Dryopteridaceae) in China. Acta Phytotax Geobot 69:127-133
Hori K, Zhou XL, Yan YH, Inoue Y, Murakami N (2018c) Evidence for maternal ability in hybridization of apogamous fern species: Dryopteris tsushimense K. Hori & N. Murak. and D. subtsushimense K. Hori & N. Murak. (Dryopteridaceae), new tetraploid apogamous pteridophytes of hybrid origin from Tsushima, Japan. Acta Phytotax Geobot 69:143-160
Ishikawa H, Watano Y, Kano K, Ito M, Kurita S (2002) Development of primer sets for PCR amplification of the PgiC gene in ferns. J Plant Res 115:65-70
IUCN (2019) The IUCN Red List of Threatened Species. Version 2019-1. http://www.iucnredlist.org. Downloaded on 21 March 2019
Iwatsuki K, Yamazaki T, Boufford DE, Ohba H (1995) Flora of Japan, vol I. Kodansha, Tokyo
Izuno A, Takamiya M, Kaneko S, Isagi Y (2012) Genetic variation and structure of the endangered lady fern Athyrium viridescentipes based on ubiquitous genotyping. J Plant Res 125:613-618
Jaruwattanaphan T, Matsumoto S, Watano Y (2013) Reconstructing hybrid speciation events in the Pteris cretica group (Pteridaceae) in Japan and adjacent regions. Syst Bot 38:15-27
Knapp R (2014) Commented list of Pteridophytes of Taiwan (ed. 3.1) https://sites.google.com/site/fernsoftaiwan/
Kuo LY, Chen CW, Shinohara W, Ebihara A, Kudoh H, Sato H, Huang YM, Chiou WL (2017) Not only in the temperate zone: independent gametophytes of two vittarioid ferns (Pteridaceae, Polypodiales) in East Asian subtropics. J Plant Res 130:255-262
Kuo LY, Ebihara A, Hsu TC, Rouhan G, Huang YM, Wang CN, Chiou WL, Kato M (2018) Infrageneric revision of the fern genus Deparia (Athyriaceae, Aspleniineae, Polypodiales). Syst Bot 43:645-655
Kuo LY, Ebihara A, Shinohara W, Rouhan G, Wood KR, Wang CN, Chiou WL (2016) Historical biogeography of the fern genus Deparia (Athyriaceae) and its relation with polyploidy. Molec Phylogen Evol 104:123-134
Kuo LY, Huang YM (2017) Determining genome size from spores of seedless vascular plants. Bio Prtocol 7(11):e2322
Kurata S, Nakaike T (1979) Illustrations of Pteridophytes of Japan, vol 1. University of Tokyo Press, Tokyo (in Japanese)
Kurata S, Nakaike T (1981) Illustrations of Pteridophytes of Japan, vol 2. University of Tokyo Press, Tokyo (in Japanese)
Kurata S, Nakaike T (1983) Illustrations of Pteridophytes of Japan, vol 3. University of Tokyo Press, Tokyo (in Japanese)
Kurata S, Nakaike T (1985) Illustrations of Pteridophytes of Japan, vol 4. University of Tokyo Press, Tokyo (in Japanese)
Kurata S, Nakaike T (1987) Illustrations of Pteridophytes of Japan, vol 5. University of Tokyo Press, Tokyo (in Japanese)
Kurata S, Nakaike T (1990) Illustrations of Pteridophytes of Japan, vol 6. University of Tokyo Press, Tokyo (in Japanese)
Kurata S, Nakaike T (1994) Illustrations of Pteridophytes of Japan, vol 7. University of Tokyo Press, Tokyo (in Japanese)
Kurata S, Nakaike T (1997) Illustrations of Pteridophytes of Japan, vol 8. University of Tokyo Press, Tokyo (in Japanese)
Kurita S (1963) Cytotaxonomy of Japanese Coniogramme Fée. J Jpn Bot 38:42-46
Kurita S (1972) Chromosome numbers of some Japanese ferns (8). Ann Rep For Stud　Coll Chiba Univ 7:47-53
Le Péchon T, He H, Zhang L, Zhou XM, Gao XF, Zhang LB (2016) Using a multilocus phylogeny to test morphology-based classifications of Polystichum (Dryopteridaceae), one of the largest fern genera. BMC Evol Biol 16:55
Lehnert M, Krug M, Kessler M (2017) A review of symbiotic fungal endophytes in lycophytes and ferns--a global phylogenetic and ecological perspective. Symbiosis 71:77-89
Lin SJ, Kato M, Iwatsuki K (1994) A taxonomic study of the fern genus Sphenomeris (Lindsaeaceae) in Japan. J Jpn Bot 69:127-141
Lin SJ, Kato M, Iwatsuki K (1996) Electrophoretic evidence for the origins of tetraploids and hybrids of Sphenomeris chinensis sensu lato (Lindsaeaceae) in Japan. J Plant Res 109:201-209
Lin YX, Viane R (2013) Aspleniaceae. Pp. 267-316 in Wu ZY, Raven PH, Hong DY eds., Flora of China, Vol. 2-3 (Pteridophytes). Beijing: Science Press; St. Louis: Missouri Botanical Garden Press
Makino T, Nemoto K (1925) Nippon-Shokubutsu-Soran (Flora of Japan) with Descriptions of Every Plant Phanerograms and Higher Cryptogams Indigenous to, Introduced into and Cultivated in the Empire of Japan Kabafuto, Hokkaido, Honshu, Shikoku, Kiushiu, Riukiu and Taiwan. Nippon-Shokubutsu-Soran Kankokai, Tokyo (in Japanese)
Manton I (1950) Problems of Cytology and Evolution in the Pteridophyta. Cambridge University Press
Masuyama S (1983) The gametophyte of Pleurosoriopsis makinoi (Maxim.) Fomin. J Jpn Bot 50:105-114
Masuyama S, Watano Y (2010) Cryptic species in the fern Ceratopteris thalictroides (L.) Brongn. (Parkeriaceae). IV. Taxonomic revision. Acta Phytotax Geobot 61:75-86
Matsumoto S (2003) Species ecological study on reproductive systems and speciation of Cyrtomium falcatum complex (Dryopteridaceae) in Japanese Archipelago. Ann Tsukuba Bot Gard 22:1-141 (in Japanese with English summary)
Ministry of the Environment, Japan (2019) Red List of Japan, 2019 https://www.env.go.jp/press/106383.html (in Japanese)
Mitsuta S (1986) A preliminary report on reproductive type of Cyrtonium (Dryopteridaceae). Acta Phytotax Geobot 37:117-122 (in Japanese with English summary)
Momose S (1967) Prothallia of the Japanese Ferns (Filicales). University of Tokyo Press, Tokyo (in Japanese)
Mountier CF, Case BS, Perrie L, Brownsey P, Paterson AM, Curran TJ, Buckley HL (2018) Patterns of range size in New Zealand ferns and lycophytes. NZ J Ecol 42:248-261
Murakami K, Matsui R, Morimoto Y (2007) Northward invasion and range expansion of the invasive fern Thelypteris dentata (Forssk.) St. John into the urban matrix of three prefectures in Kinki District, Japan. Amer Fern J 97:186-199
Murakami N, Watanabe M, Yokoyama J, Yatabe Y, Iwasaki H, Serizawa S (1999) Molecular taxonomic study and revision of the three Japanese species of Asplenium sect. Thamnopteris. J Plant Res 112:15-25
Nakai T, Momose S (1937) A morphological and taxonomical study on Japanese Microlepia. Cytologia Fujii Jubilaei:360-365
Nakato N, Ebihara A (2016) Chromosome numbers of 18 ferns in Japan: toward completion of chromosome information in Japanese ferns. Bull Natl Mus Nat Sci B 42:25-40
Nitta JH, Ebihara A, Ito M (2011) Reticulate evolution in the Crepidomanes minutum species complex (Hymenophyllaceae). Amer J Bot 98:1782-1800
Ogura-Tsujita Y, Sakoda A, Ebihara A, Yukawa T, Imaichi R (2013) Arbuscular mycorrhiza formation in cordate gametophytes of two ferns, Angiopteris lygodiifolia and Osmunda japonica. J Plant Res 126:41-50
Ogura-Tsujita Y, Hirayama Y, Sakoda A, Suzuki A, Ebihara A, Morita N, Imaichi R (2016) Arbuscular mycorrhizal colonization in field-collected terrestrial cordate gametophytes of pre-polypod leptosporangiate ferns (Osmundaceae, Gleicheniaceae, Plagiogyriaceae, Cyatheaceae). Mycorrhiza  26:87-97
Ohta N, Takamiya M (1999) Taxonomic studies of the Diplazium mettenianum complex (Woodsiaceae; Pteridophyta) in Japan: Morphology, cytology and taxonomy of plants with normal-shaped spores. J Plant Res 112:67-86
Park CH, Kato M (2003) Apomixis in the interspecific triploid hybrid fern Cornopteris christenseniana (Woodsiaceae). J Plant Res 116:93-103
Perrie LR, Shepherd LD, Brownsey PJ (2015) An expanded phylogeny of the Dennstaedtiaceae ferns: Oenotrichia falls within a non-monophyletic Dennstaedtia, and Saccoloma is polyphyletic. Austral Syst Bot 28:256-264
Pressel S, Bidartondo MI, Field KJ, Rimington WR, Duckett JG (2016) Pteridophyte fungal associations: current knowledge and future perspectives. J Syst Evol 54:666-678
The Pteridophyte Phylogeny Group (2016) A community-derived classification for extant lycophytes and ferns. J Syst Evol 54:563-606
Rothfels CJ, Pryer KM, Li FW (2017) Next-generation polyploid phylogenetics: rapid resolution of hybrid polyploid complexes using PacBio single-molecule sequencing. New Phytol 213:413-429
Sahashi N (1983) Morphological and taxonomical studies on Ophioglossales in Japan and the adjacent regions (9). Additional notes on Sceptridium in Isl. Oshima, Izu Islands. J Jpn Bot 58:338-344
Serizawa S (2015) Misecellaneous notes on Japanese pteridophytes (6). Shidekobushi 3:39-59
Shinohara W, Takamiya M, Murakami N (2003) Taxonomic study of Japanese Deparia petersenii (Woodsiaceae) based on cytological and molecular information. Acta Phytotax Geobot 54:137-148
Shinohara W, Ushio Y, Seo A, Nakato N, Kono M, Kudoh H, Tobe H, Murakami N (2010) Evidence for hybrid origin and segmental allopolyploidy in eutetraploid and aneutetraploid Lepisorus thunbergianus (Polypodiaceae). Syst Bot 35: 20-29
Shrestha N, Zhang XC (2015) Recircumscription of Huperzia serrata complex in China using morphological and climatic data. J Syst Evol 53:88-103
Sigel EM (2016) Genetic and genomic aspects of hybridization in ferns. J Syst Evol 54:638-655
Suzuki T, Watanabe I, Shiraiwa T (2005) Allozyme types of water fern Azolla japonica and its relatives (Azollaceae) growing in Japan. Acta Phytotax Geobot 56:71-83
Tagawa M (1959) Coloured Illustrations of the Japanese Pteridophyta. Hoikusha, Osaka (in Japanese)
Namegata T, Kurata S (1961) Enumeration of the Japanese Pteridophytes. In: Namegata T (ed) Collection and 
Takahashi N, Imaichi R (2007) Developmental morphology of young gametophytes of Botrychium microphyllum in axenic culture. J Jpn Women's Univ Fac Sci 15:45-49
Takamiya M (1989) Cytological and ecological studies on the speciation of Lycopodium clavatum L. in the Japanese Archipelago. J Sci Hiroshima Univ B2 22:353-430
Takamiya M (1996) Index to chromosomes of Japanese Pteridophyta (1910-1996). Japan Pteridological Society, Tokyo
Takamiya M, Ohta N (2001) Cytological and reproductive studies of Japanese Diplazium (Woodsiaceae; Pteridophyta). III. The cytological complexity of species groups with simply pinnate to bipinnatifid leaves. J Plant Res 114:443-457
Takamiya M, Watanabe M, Ono K (1997) Biosystematic studies on the genus Isoetes (Isoetaceae) in Japan IV. Morphology and anatomy of sporophytes, phytogeograohy and taxonomy. Acta Phytotax Geobot 48:89-122
Takatsuki S (2009) Effects of sika deer on vegetation in Japan: A review. Biol Conserv 142:1922-1929
Tanaka T, Isaka Y, Hattori M, Sato T (2014) Ecological and phylogenetic approaches for diversification of apogamous ferns in Japan. Plant Syst Evol 300: 2041-2050 
Terada Y, Takamiya M (2006) Cytological and genetic study of two putative hybrids and their parents of Athyrium (Woodsiaceae; Pteridophyta) in Tsai JL, Shieh WC (1985) A cytotaxonomic survey of the fern family Aspidiaceae (sensu Copeland) in Taiwan. J Sci Engin 22:121-144
Yakushima Island, southwestern Japan. Acta Phytotax Geobot 57:95-106
Thunberg CP (1786) Flora Japonica sistens Plantas Insularum Japonicarum. In Bibliopolio I. G. Muelleriano, Leipzig
Ueno K, Ueno Y, Ebihara A (2019) Dennstaedtia punctilobula (Dennstaedtiaceae), newly naturalized in Nagano Prefecture, Japan. J Jpn Bot 94:58-60
Wagner WH Jr (1954) Reticulate evolution in the Appalachian Aspleniums. Evolution 8:103-118
Wang L, Qi XP, Xiang QP, Heinrichs J, Schneider H, Zhang XC (2010) Phylogeny of the paleotropical fern genus Lepisorus (Polypodiaceae, Polypodiopsida) inferred from four chloroplast DNA regions. Molec Phylogen Evol 54:211-225
Wei R, Schneider H, Zhang XC (2013) Toward a new circumscription of the twinsorus-fern genus Diplazium (Athyriaceae): A molecular phylogeny with morphological implications and infrageneric taxonomy. Taxon 62:441-457
Wu ZY, Raven PH, Hong D (2013) Flora of China, Volumes 2 - 3, Lycopodiaceae through Polypodiaceae. Science Press & Missouri Botanical Garden Press
Xu KW, Zhang L, Lu NT, Zhou XM, He H, Luong TT, Knapp R, Liao WB, Zhang LB (2018) Nine new species of Hymenasplenium (Aspleniaceae) from Asia. Phytotaxa 358:1-25
Yatabe Y, Tsutsumi C, Hirayama Y, Mori K, Murakami N, Kato M (2009) Genetic population structure of Osmunda japonica, rheophilous Osmunda lancea and their hybrids. J Plant Res 122:585-595
Yatabe Y, Yamamoto K, Tsutsumi C, Shinohara W, Murakami N, Kato M (2011) Fertility and precocity of Osmunda × intermedia offspring in culture. J  Plant Res 124:265-268
Yoroi R (1972) Studies on spore germination and gametophyte of Japanese Hymenophyllaceae. Sci Rep Tokyo Kyoiku Daigaku B 225:81-110
Yoroi R (1975) Spore germination and gametophyte development of the Vittariaceae (1). J Jpn Bot 50:33-43
Yoroi R (1976) Gametophyte and apogamous embryo of Crepidomanes latemarginale from Isl. Ishigaki, Ryukyu. J Jpn Bot 51:257-267
Yoroi R (1992) Gametophyte and Embryo of Microgonium tahitense (Hymenophyllaceae). J Jpn Bot 67:169-176
Zhang L, Lu NT, Zhou XM, Chen DK, Knapp R, Zhou L, Guo L, Luong TT, Sun H, Gao XF, Zhang LB (2019) A plastid phylogeny of the Old World fern genus Leptochilus (Polypodiaceae): Implications for cryptic speciation and progressive colonization from lower to higher latitudes. Molec Phylogen Evol 134:311-322
Zhou S, Dong W, Chen X, Zhang X, Wen J, Schneider H (2014) How many species of bracken (Pteridium) are there? Assessing the Chinese brackens using molecular evidence. Taxon 63:509-521

Fig. 1. Maps indicating fern and lycophyte diversity in Japan on 10-km grid maps. a. Richness of native fern and lycophyte taxa. b. Phylogenetic diversity of fern and lycophyte taxa on an unrooted Bayesian tree. c. Phylogenetic diversity of fern taxa on an Bayesian tree rooted by a lycophyte (Lycopodium clavatum var. nipponicum). d. Richness of apomictic fern taxa. e. Proportion of apomicitic taxa to all the taxa. f. Richness of threatened taxa included in the national red list of Japan. 

Electronic supplementary material 1. A list of native fern and lycophyte taxa (species, subspecies and varieties) in Japan accepted in this study. Taxon ID refers that in FernGreenList ver.1.0.1 (http://www.rdplants.org/gl/). Otherwise noted, rbcL GenBank accession numbers are those used in Ebihara et al. (2010). Information on reproductive modes and ploidy levels follow those in Ebihara et al. (2016, 2017), and only the records based on material collected in Japan are accepted. For reproductive mode, irregular meiosis is not considered, 0 = no information, 1 = sexual, 2 = apomictic and 3 = sexual + apomictic. 

Electronic supplementary material 2. A list of herbarium specimens of 720 native fern and lycophyte taxa in Japan which the distribution maps in ca. 10-km grids in Ebihara et al. (2016, 2017) based on. Small number of corrections on identification and location after the publication were applied, but findings (e.g. new species and new records) after the publication are not reflected. Taxon ID refers that in FernGreenList ver.1.0.1 (http://www.rdplants.org/gl/). Secondary grid code of Japan (http://www.stat.go.jp/english/data/mesh/05.html) and coordinates of their center points are listed. Herbarium acronyms follow Index Herbariorum (http://sweetgum.nybg.org/science/ih/) but the following abbreviations are used for those not listed in Index Herbariorum; Gifu: Gifu Prefectural Museum; Gunma: Gunma Museum of Natural History; Iwate: Iwate Prefectural Museum; Kobe: Kobe University; Kurashiki: Kurashiki Museum of Natural History; Miyajima: Miyajima Natural Botanical Garden, Hiroshima University, Niigata: Niigata University; Sendai City Wild Plants Garden; Tochigi: Tochigi Prefectural Museum; Yamaguchi: Yamaguchi Prefectural Museum; Yokohama; Yokohama City Children’s Botanical Garden; Yokosuka: Yokosuka City Museum. All the listed specimens were seen by the authors except for a part of Isoetes specimens which are cited from Takamiya et al. (1997).  

Electronic supplementary material 3. JpFernKeys ver. 1.0: An interactive key file for identification of all the native fern and lycophyte taxa (species, subspecies and varieties) in Japan plus a few common naturalized species for the software Lucid v3.3 (free edition) available at http://www.lucidcentral.com. The data are excerpts from matrices of morphological characters included in Ebihara (2016, 2017). The measurements were based on each ten fertile herbarium specimens collected in Japan which were selected randomly with a few exceptions for the species bearing large fronds (e.g. tree ferns). For some rare species with less than ten specimens available, those collected outside Japan were used. 


