# Load packages
library(conflicted)
library(checkr)
library(FD)
library(here)
library(assertthat)
library(ape)
library(readxl)
library(janitor)
library(maps)
library(picante)
library(jntools)
library(broom)
library(assertr)
library(magrittr)
library(sf)
library(phyloregion)
library(scico)
library(clustermq)
library(magrittr)
library(glue)
library(patchwork)
library(rcartocolor)
library(ggtext)
library(ggridges)
library(tidyverse)

# Resolve conflicts
conflicted::conflict_prefer("map", "purrr")
conflicted::conflict_prefer("select", "dplyr")
conflicted::conflict_prefer("filter", "dplyr")
conflicted::conflict_prefer("gather", "tidyr")
conflicted::conflict_prefer("extract", "magrittr")
